version: '3'
services:
  front-next-test:
    image: dragonchat-front-test:0.0.2
    container_name: dragonchat-front-test
    build: ./Dockerfile.test
    restart: unless-stopped
    ports:
      - 5005:5005
    environment:
      - PORT=5005
      - NEXT_PUBLIC_API_SENDER_SOCKET_URL=$NEXT_PUBLIC_API_SENDER_SOCKET_URL
      - NEXT_PUBLIC_API_SENDER_URL=$NEXT_PUBLIC_API_SENDER_URL
      - NEXT_PUBLIC_API_USER_URL=$NEXT_PUBLIC_API_USER_URL
      - NEXT_PUBLIC_LOGIN_COOKIE_NAME=$NEXT_PUBLIC_LOGIN_COOKIE_NAME
      - NODE_ENV=$NODE_ENV
    volumes:
      - 'frontend:/home/app-frontend-test'
      - '/home/app-frontend-test/node_modules'
    networks:
      - nginx-proxy-manager_npm
networks:
  nginx-proxy-manager_npm:
    external: true
volumes:
  frontend:
