version: '3'
services:
  front-next:
    container_name: dragonchat-front-session
    build:
      context: .
      dockerfile: Dockerfile.test
    restart: unless-stopped
    ports:
      - "5006:5006"
    environment:
      - NODE_ENV=production
      - PORT=5006
    volumes:
      - '.:/app/session'
      - '/app/session/node_modules'
    networks:
      - nginx-proxy-manager_npm
networks:
  nginx-proxy-manager_npm:
    external: true
