FROM node:16-alpine AS deps
WORKDIR /app-frontendts

COPY package*.json ./
RUN npm install
COPY . .



FROM node:16-alpine AS builder
WORKDIR /app-frontendts
COPY --from=deps /app-frontendts ./
RUN npm run build


FROM node:16-alpine AS runner
WORKDIR /app
#ENV NODE_ENV production

COPY --from=builder /app-frontendts/package*.json ./
COPY --from=builder /app-frontendts/public ./public
COPY --from=builder /app-frontendts/.next ./.next
RUN npm install next

CMD ["npm","run","start"]
