# Utilizamos la imagen de Node.js 16 en Alpine Linux como base para la imagen de pruebas
FROM node:16-alpine

# Establecemos el directorio de trabajo
WORKDIR /app

# Copiamos el archivo package.json y package-lock.json
COPY package*.json ./

# Instalamos las dependencias necesarias para la aplicación, incluyendo las dependencias de desarrollo
RUN npm ci
RUN npm install next

# Copiamos la aplicación
COPY . .

# Generamos los archivos necesarios para la aplicación
#RUN npm run build

# Iniciamos las pruebas
CMD ["npm", "run", "dev"]
