services:
  dragonchat-front:
    image: dragonchat-front:${IMAGE_TAG}
    container_name: dragonchat-front
    build: .
    restart: unless-stopped
    ports:
      - $PORT:$PORT
    env_file:
      - .env
    networks:
          mynet: {}


networks:
    mynet:
        name: ${API_WSP_NETWORK}
        external: true
