version: '3'
services:
  dragonchat-front:
    image: dragonchat-front:${IMAGE_TAG}
    container_name: dragonchat-front
    build: .
    restart: unless-stopped
    ports:
      - $PORT:$PORT
    environment:
      - PORT=$PORT
      - NEXT_PUBLIC_API_SENDER_SOCKET_URL=$NEXT_PUBLIC_API_SENDER_SOCKET_URL
      - NEXT_PUBLIC_API_SENDER_URL=$NEXT_PUBLIC_API_SENDER_URL
      - NEXT_PUBLIC_API_USER_URL=$NEXT_PUBLIC_API_USER_URL
      - NEXT_PUBLIC_LOGIN_COOKIE_NAME=$NEXT_PUBLIC_LOGIN_COOKIE_NAME
    networks:
          mynet: {}


networks:
    mynet:
        name: ${API_WSP_NETWORK}
        external: true
