version: '3'
services:
  front-next:
    image: dragonchat-front
    container_name: dragonchat-front
    build: .
    env_file:
      - ./.env
      - ./.env.local
    ports:
      - 5004:5004
    volumes:
      - '.:/home/app-frontend'
      - '/home/app-frontend/node_modules'
    networks:
      - nginx-proxy-manager_npm
networks:
  nginx-proxy-manager_npm:
    external: true
