version: '3'
services:
  front-next:
    image: dragonchat-front
    container_name: dragonchat-front
    build: .
    restart: unless-stopped
    ports:
      - $PORT:$PORT
    environment:
      - PORT=$PORT
    volumes:
      - '.:/home/app-frontend'
      - '/home/app-frontend/node_modules'
    networks:
      - nginx-proxy-manager_npm
networks:
  nginx-proxy-manager_npm:
    external: true
