version: '3.1'
services:
  front-next-test:
    image: dragonchat-front-test:0.0.1
    container_name: dragonchat-front-test
    build: .
    restart: unless-stopped
    ports:
      - $PORT:$PORT
    environment:
      - PORT=$PORT
      - NEXT_PUBLIC_API_SENDER_SOCKET_URL=$NEXT_PUBLIC_API_SENDER_SOCKET_URL
      - NEXT_PUBLIC_API_SENDER_URL=$NEXT_PUBLIC_API_SENDER_URL
      - NEXT_PUBLIC_API_USER_URL=$NEXT_PUBLIC_API_USER_URL
      - NEXT_PUBLIC_LOGIN_COOKIE_NAME=$NEXT_PUBLIC_LOGIN_COOKIE_NAME
      - NODE_ENV=$NODE_ENV
    volumes:
      - 'test_frontend:/home/app-frontend-test'
      - '/home/app-frontend-test/node_modules'
    networks:
      - nginx-proxy-manager_npm
networks:
  nginx-proxy-manager_npm:
    external: true
volumes:
  test_frontend:
