FROM node:16-alpine AS deps
WORKDIR /app-frontend

COPY package*.json ./
RUN npm install
COPY . .



FROM node:16-alpine AS builder
WORKDIR /app
COPY --from=deps /app-frontend ./
RUN npm run build


FROM node:16-alpine AS runner
WORKDIR /app
#ENV NODE_ENV production

COPY --from=builder /app-frontend/package*.json ./
COPY --from=builder /app-frontend/public ./public
COPY --from=builder /app-frontend/.next ./.next
RUN npm install next

CMD ["npm","run","start"]