version: '3'
services:
  front-next-test:
    image: dragonchat-front-test:0.0.2
    container_name: dragonchat-front-test
    build:
      context: .
      dockerfile: Dockerfile.test
    restart: unless-stopped
    ports:
      - 5005:5005
    environment:
      - PORT=5005
      - NODE_ENV=development
    volumes:
      - 'frontend:/home/app-frontend-test'
      - '/home/app-frontend-test/node_modules'
    networks:
      - nginx-proxy-manager_npm
networks:
  nginx-proxy-manager_npm:
    external: true
volumes:
  frontend:
